# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Bloomle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build LR1_TestCode1/LR1_TestCode1/LR1_TestCode1.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish LR1_TestCode1/LR1_TestCode1/LR1_TestCode1.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Reveal Azure IDs
        run: |
          echo "Tenant:" && echo "${{ secrets.AZUREAPPSERVICE_TENANTID_824C6D72DB124912A7F76A1D7AB61635 }}" | sed 's/./& /g'
          echo "Subscription:" && echo "${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_909EBBFC58FD42AEB1FEC223C0A98D97 }}" | sed 's/./& /g'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7641F758560349EF96DF14AD8A663733 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_824C6D72DB124912A7F76A1D7AB61635 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_909EBBFC58FD42AEB1FEC223C0A98D97 }}

      - name: Get Owner Email
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az role assignment list --all --query "[?roleDefinitionName=='Owner'].{Principal:principalName, Type:principalType}" -o table

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Bloomle'
          slot-name: 'Production'
          package: .